export const LIST_SETTINGS_REQUEST = "LIST_SETTINGS_REQUEST";
export const LIST_SETTINGS_SUCCESS = "LIST_SETTINGS_SUCCESS";
export const LIST_SETTINGS_FAIL = "LIST_SETTINGS_FAIL";

export const CONFIGURE_STKPUSH_REQUEST = "CONFIGURE_STKPUSH_REQUEST";
export const CONFIGURE_STKPUSH_SUCCESS = "CONFIGURE_STKPUSH_SUCCESS";
export const CONFIGURE_STKPUSH_FAIL = "CONFIGURE_STKPUSH_FAIL";
