export const CREATE_SOURCE_REQUEST = "CREATE_SOURCE_REQUEST";
export const CREATE_SOURCE_SUCCESS = "CREATE_SOURCE_SUCCESS";
export const CREATE_SOURCE_FAIL = "CREATE_SOURCE_FAIL";

export const GET_SOURCES_REQUEST = "GET_SOURCES_REQUEST";
export const GET_SOURCES_SUCCESS = "GET_SOURCES_SUCCESS";
export const GET_SOURCES_FAIL = "GET_SOURCES_FAIL";

export const DELETE_SOURCE_REQUEST = "DELETE_SOURCE_REQUEST";
export const DELETE_SOURCE_SUCCESS = "DELETE_SOURCE_SUCCESS";
export const DELETE_SOURCE_FAIL = "DELETE_SOURCE_FAIL";
