export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const MAKE_ADMIN_REQUEST = "MAKE_ADMIN_REQUEST";
export const MAKE_ADMIN_SUCCESS = "MAKE_ADMIN_SUCCESS";
export const MAKE_ADMIN_FAIL = "MAKE_ADMIN_FAIL";

export const REMOVE_ADMIN_REQUEST = "REMOVE_ADMIN_REQUEST";
export const REMOVE_ADMIN_SUCCESS = "REMOVE_ADMIN_SUCCESS";
export const REMOVE_ADMIN_FAIL = "REMOVE_ADMIN_FAIL";
